---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: unifi
  labels:
    app: mongodb
spec:
  template:
    spec:
      containers:
        - name: mongodb
          # track version in this environment explicitly
          image: docker.io/mongo:8.0.19@sha256:b3f7ad203b34c4519d235df0ba63834235f91ba8a9c23be67e22ecc861524173
