---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: unifi
  labels:
    app: mongodb
spec:
  template:
    spec:
      containers:
        - name: mongodb
          # track version in this environment explicitly
          image: docker.io/mongo:8.0.20@sha256:22cab4837b4b9119395372e4a14ceb50d8abbf4b29a41ca7f3d504cbab95caeb
