---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: unifi
  labels:
    app: mongodb
spec:
  template:
    spec:
      containers:
        - name: mongodb
          # track version in this environment explicitly
          image: docker.io/mongo:8.0.5@sha256:7bd28e5eea1c5766a084d5818254046f3ebe3b8f20a65e3a274640189e296667
