---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: unifi-controller
  namespace: unifi
  labels:
    app: unifi-controller
spec:
  template:
    spec:
      containers:
        - name: unifi-network-application
          # track version in this environment explicitly
          image: lscr.io/linuxserver/unifi-network-application:10.1.89@sha256:f86da30498d3f6c00b403e6d2e32dfd012b531f87cad5bd9a270c35aceedbd7a
