queue_rules: []
pull_request_rules:
  - name: Automatic Merge for HEAD environment
    conditions:
      - label=env:head            # PR must have this label
    actions:
      merge:
        method: squash            # Choose  merge, squash or rebase
  - name: Auto-Merge minor not flagged for automerge:off
    conditions:
      - label=updateType:minor    # PR must have this label
      - label!=automerge:off      # PR must not have this label
    actions:
      merge:
        method: squash            # Choose  merge, squash or rebase
