---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: flux-system

resources:
  - ../../../../../../apps/diag/whoami/flux
  - ../../../../../../apps/dns/adguard/flux
  - ../../../../../../apps/dns/unbound/flux
  - ../../../../../../apps/finances/actualbudget/flux
  - ../../../../../../apps/monitoring/checkmk-agent/flux
  - ../../../../../../apps/monitoring/metrics-server/flux
  - ../../../../../../apps/network/unifi-controller/flux
