---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: unifi
  labels:
    app: mongodb
spec:
  template:
    spec:
      containers:
        - name: mongodb
          image: mongo:8.2.5@sha256:3a7947f3211e70c045ebff7e94293298bc3fa4e08e5cfcb8cb32ca0d06e06635
      nodeSelector:
        topology.kubernetes.io/zone: pve5
