apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# do not include components as hostname transformation would not work
# in HTTPRoute which is missing this stanza in the redirect definition
#
# components:
#   - ../../../../../components/envs/rebuild

resources:
  - ../../base
