---
apiVersion: v1
kind: Service
metadata:
  name: ssh
  namespace: ssh
  annotations:
    io.cilium/lb-ipam-ips: 192.168.8.22
spec:
  type: LoadBalancer
  selector:
    app: ssh
  ports:
    - name: ssh
      port: 22
      targetPort: ssh
