apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: &name actualbudget
name: *name
# namespace setting only supported to limited extent by helm chart templates,
# which are needed by `kustomize build --enable helm` (using `helm template`)
# setting it anyway for argo/flux
namespace: *name
repo: https://community-charts.github.io/helm-charts
releaseName: *name
version: 1.9.1    # renovate: helm=actualbudget registry=https://community-charts.github.io/helm-charts
## do not use valuesFile as it's not inherited in overlays
# valuesFile: values.yaml
## only inline values are inherited in overlays
valuesInline:
  image:
    tag: "26.7.0" # renovate: docker=ghcr.io/actualbudget/actual-server versioning=loose

  persistence:
    enabled: true
    size: 1Gi
    storageClass: longhorn-standard

  strategy:
    type: Recreate
