apiVersion: apps/v1
kind: Deployment
metadata:
  name: ssh
  namespace: diag
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: ssh
          image: lscr.io/linuxserver/openssh-server:latest@sha256:68b605929e83b2efe000da09269688f6d82a44579e8a18e2d9e8c8d272917cf7
