apiVersion: apps/v1
kind: Deployment
metadata:
  name: ssh
  namespace: diag
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: ssh
          image: lscr.io/linuxserver/openssh-server:latest@sha256:fdd9783e0fa4c52592c8405765c5de04dcf657db1b4d6ab073c14c4b998ca1fa
