apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - egress-gw-policy.yaml

components:
  - ../../../../../_components/dev

patches:
  - path: svc.yaml
  - path: deployment.yaml