---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: sealed-secrets
spec:
  interval: 1h
  ref:
    tag: 2.19.1
  url: oci://registry-1.docker.io/bitnamicharts/sealed-secrets
