---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: proxmox-csi-plugin
spec:
  interval: 1h
  ref:
    tag: 0.5.10
    digest: sha256:618944174ec6f568f1ef739a83d900ccc2bfd6c7130e5bac29e3ff66f27b8da4
  url: oci://ghcr.io/sergelogvinov/charts/proxmox-csi-plugin

