apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

components:
  - ../../../../../components/envs/qa

resources:
  - ../../base
  - minio-backup-secret-sealed.yaml

patches:
  - path: backup-target.yaml
