apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: longhorn-system

resources:
  - job-backup-default.yaml
  - job-fs-trim-default.yaml
  - job-snapshot.yaml
  - sc-ext4.yaml
  - sc-fast.yaml
  - sc-ha.yaml
  - sc-standard.yaml
  - sc-xfs.yaml
