---
apiVersion: cilium.io/v2alpha1
kind: CiliumBGPAdvertisement
metadata:
  name: bgp-advertisements
  labels:
    advertise: bgp
spec:
  advertisements:
    - advertisementType: "Service"
      service:
        addresses: # <-- specify the service types to advertise
          - LoadBalancerIP
      selector: # <-- select all services
        matchExpressions:
          - {key: somekey, operator: NotIn, values: ["never-used-value"]}
