# replace .spec.interval of all Flux Kustomizations with the value of FLUX_RECONCILIATION_INTERVAL from the cluster-param ConfigMap 
- source:
    kind: ConfigMap
    name: cluster-param
    fieldPath: data.FLUX_RECONCILIATION_INTERVAL
  targets:
    - select:
        apiVersion: kustomize.toolkit.fluxcd.io/v1
        kind: Kustomization
      fieldPaths:
        - spec.interval