apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# DISABLED: do not prefix name nor do other env.-specific transformations
# components:
#   - ../../../../../_components/qa

resources:
  - ../../base