apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ns.yaml
  - pvc-db.yaml
  - deployment-db.yaml
  - deployment-frontend.yaml
  - svc-db.yaml
  - svc-frontend.yaml

configMapGenerator:
  - name: mongodb-init
    namespace: unifi
    files:
      - assets/init-mongo.js
