apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-data
  namespace: unifi
spec:
  storageClassName: proxmox-csi
  volumeName: pv-mongodb
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 400M
