---
apiVersion: v1
kind: Service
metadata:
  name: unifi-controller
  namespace: unifi
  annotations:
    io.cilium/lb-ipam-ips: 192.168.8.20
spec:
  type: LoadBalancer
  selector:
    app: unifi-controller
  ports:
    - name: https-alt
      port: 8443
      targetPort: web-admin
