---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: unifi-controller
spec:
  interval: 1h
  path: ./k8s/apps/network/unifi-controller/base
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: true
  dependsOn:
    - name: cilium
    - name: gateway-api
    - name: proxmox-csi
    - name: sealed-secrets
