apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# needed by configMapGenerator
namespace: adguard

components:
  - ../../../../../components/envs/qa

resources:
  - ../../base

patches:
  - path: svc.yaml
  - path: merge-deployment.yaml

configMapGenerator:
  - name: adguard-config-local
    files:
      - config/AdGuardHome.yaml
