---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: flux-system

resources:
  - ../../../../../../infra/controller/cert-manager-core/flux
  - ../../../../../../infra/controller/cert-manager/flux
  - ../../../../../../infra/controller/flux-instance/flux
  - ../../../../../../infra/controller/flux-operator/flux
  - ../../../../../../infra/controller/kubelet-serving-cert-approver/flux
  - ../../../../../../infra/network/gateway/flux
  - ../../../../../../infra/network/gateway-redirect/flux
  - ../../../../../../infra/storage/longhorn-core/flux
  - ../../../../../../infra/storage/longhorn/flux
  - ../../../../../../infra/storage/proxmox-csi/flux
