---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: flux-system

resources:
  - ../../../../../../core/controller/sealed-secrets/flux
  - ../../../../../../core/network/cilium-core/flux
  - ../../../../../../core/network/cilium/flux
  - ../../../../../../core/network/gateway-api-crds/flux
