apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

components:
  - ../../../../../_components/dev

patches:
  - path: deployment-db.yaml
  - path: svc-frontend.yaml
