instance:
  distribution:
    artifact: oci://ghcr.io/controlplaneio-fluxcd/flux-operator-manifests:v0.55.0
  cluster:
    networkPolicy: false
    size: small
  components:
    - source-controller
    - kustomize-controller
    - helm-controller
    - notification-controller
  sync:
    kind: GitRepository
    url: "https://github.com/isejalabs/homelab"
    ref: "refs/heads/issue/808_fluxcd"
    path: "k8s/infra/controller/fluxcd/cluster/envs/REPLACE_ME"
    interval: 10m
