apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/helm

helmCharts:
  - name: checkmk
    version: 1.9.0
    repo: https://checkmk.github.io/checkmk_kube_agent
    releaseName: "checkmk-kube-agent"
    namespace: checkmk-agent

